### ISSUE TITLE
order of plugins declaration causes code generation to fail.

### ISSUE THREAD

**Issue by ignasi35** [lagom/grpc-sbt-experiments#3]
See https://github.com/lagom/grpc-sbt-experiments/blob/master/project/plugins.sbt#L1-L5

Declaring the `lagom-sbt-plugin` before the `sbt-protoc` causes the external process (invoking `protoc.exe`) to fail.

**Comment by ignasi35** [comment]
The issue https://github.com/scalapb/ScalaPB/issues/231 seems to confirm that multiple `protobuf-java` versions mixed in the dependency tree will cause the symptoms:

```

[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 protobuf files to /Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/target/scala-2.11/src_managed/main,/Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/target/scala-2.11/src_managed/main
[info] Compiling schema /Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/src/main/protobuf/helloworld.proto
protoc-jar: protoc version: 320, detected platform: mac os x/x86_64
protoc-jar: executing: [/var/folders/xc/46s2thrs5ss3w70292zz4bf80000gn/T/protocjar463969549639892430/bin/protoc.exe, --plugin=protoc-gen-scala=/var/folders/xc/46s2thrs5ss3w70292zz4bf80000gn/T/protocbridge5688758300906919697, --java_out=:/Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/target/scala-2.11/src_managed/main, --scala_out=java_conversions:/Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/target/scala-2.11/src_managed/main, -I/Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/src/main/protobuf, -I/Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/target/protobuf_external, /Users/ignasi/git/projects/lightbend/grpc-sbt-experiments/helloscala-lagom-client/src/main/protobuf/helloworld.proto]
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/trueaccord/scalapb/Scalapb.registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V @4: invokevirtual
  Reason:
    Type 'com/google/protobuf/GeneratedMessage$GeneratedExtension' (current frame, stack[1]) is not assignable to 'com/google/protobuf/ExtensionLite'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'com/google/protobuf/ExtensionRegistryLite' }
    stack: { 'com/google/protobuf/ExtensionRegistryLite', 'com/google/protobuf/GeneratedMessage$GeneratedExtension' }
  Bytecode:
    0x0000000: 2ab2 0009 b600 0a2a b200 0bb6 000a 2ab2
    0x0000010: 000c b600 0ab1                         

        at scalapb.ScalaPbCodeGenerator$.registerExtensions(ScalaPbCodeGenerator.scala:12)
        at protocbridge.frontend.PluginFrontend$.runWithBytes(PluginFrontend.scala:52)
        at protocbridge.frontend.PluginFrontend$.runWithInputStream(PluginFrontend.scala:67)
        at protocbridge.frontend.PosixPluginFrontend$$anonfun$prepare$1.apply$mcV$sp(PosixPluginFrontend.scala:25)
        at protocbridge.frontend.PosixPluginFrontend$$anonfun$prepare$1.apply(PosixPluginFrontend.scala:23)
        at protocbridge.frontend.PosixPluginFrontend$$anonfun$prepare$1.apply(PosixPluginFrontend.scala:23)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by ignasi35** [comment]
Using Play `2.6.3` under the covers makes this issue less likely since ScalaJS is now an OptIn dependency.
